export const cardData = [
    { title: 'Entidad num: 1', text: 'Aguscalientes', imgSrc: '/assets/icon_Aguascalientes.png'},
    { title: 'Entidad num: 2', text: 'Baja California', imgSrc: '/assets/icon_Baja_california_sur.png'},
    { title: 'Entidad num: 3', text: 'Baja California Sur', imgSrc: '/assets/icon_Baja_california.png'},
    { title: 'Entidad num: 4', text: 'Campeche', imgSrc: '/assets/icon_Campeche.png'},
    { title: 'Entidad num: 5', text: 'Coahuila', imgSrc: '/assets/icon_Coahuila.png'},
    { title: 'Entidad num: 6', text: 'Colima', imgSrc: '/assets/icon_Colima.png'},
    { title: 'Entidad num: 7', text: 'Chiapas', imgSrc: '/assets/icon_Chiapas.png'},
    { title: 'Entidad num: 8', text: 'Chihuahua', imgSrc: '/assets/icon_Chihuahua.png'},
    { title: 'Entidad num: 9', text: 'Ciudad de México', imgSrc: '/assets/icon_Ciudad_de_Mexico.png'},
    { title: 'Entidad num: 10', text: 'Durango', imgSrc: '/assets/icon_Durango.png'},
    { title: 'Entidad num: 11', text: 'Guanajuato', imgSrc: '/assets/icon_Guanajuato.png'},
    { title: 'Entidad num: 12', text: 'Guerrero', imgSrc: '/assets/icon_Guerrero.png'},
    { title: 'Entidad num: 13', text: 'Hidalgo', imgSrc: '/assets/icon_Hidalgo.png'},
    { title: 'Entidad num: 14', text: 'Jalisco', imgSrc: '/assets/icon_Jalisco.png'},
    { title: 'Entidad num: 15', text: 'México', imgSrc: '/assets/icon_Mexico.png'},
    { title: 'Entidad num: 16', text: 'Michoacán', imgSrc: '/assets/icon_Michoacan.png'},
    { title: 'Entidad num: 17', text: 'Morelos', imgSrc: '/assets/icon_Morelos.png'},
    { title: 'Entidad num: 18', text: 'Nayarit', imgSrc: '/assets/icon_Nayarit.png'},
    { title: 'Entidad num: 19', text: 'Nuevo León', imgSrc: '/assets/icon_Nuevo_Leon.png'},
    { title: 'Entidad num: 20', text: 'Oaxaca', imgSrc: '/assets/icon_Oaxaca.png'},
    { title: 'Entidad num: 21', text: 'Puebla', imgSrc: '/assets/icon_Puebla.png'},
    { title: 'Entidad num: 22', text: 'Querétaro', imgSrc: '/assets/icon_Queretaro.png'},
    { title: 'Entidad num: 23', text: 'Quintana Roo', imgSrc: '/assets/icon_Quintana_Roo.png'},
    { title: 'Entidad num: 24', text: 'San Luis Potosí', imgSrc: '/assets/icon_San_Luis_Potosi.png'},
    { title: 'Entidad num: 25', text: 'Sinaloa', imgSrc: '/assets/icon_Sinaloa.png'},
    { title: 'Entidad num: 26', text: 'Sonora', imgSrc: '/assets/icon_Sonora.png'},
    { title: 'Entidad num: 27', text: 'Tabasco', imgSrc: '/assets/icon_Tabasco.png'},
    { title: 'Entidad num: 28', text: 'Tamaulipas', imgSrc: '/assets/icon_Tamaulipas.png'},
    { title: 'Entidad num: 29', text: 'Tlaxcala', imgSrc: '/assets/icon_Tlaxcala.png'},
    { title: 'Entidad num: 30', text: 'Veracruz', imgSrc: '/assets/icon_Veracruz.png'},
    { title: 'Entidad num: 31', text: 'Yucatán', imgSrc: '/assets/icon_Yucatan.png'},
    { title: 'Entidad num: 32', text: 'Zacatecas', imgSrc: '/assets/icon_Zacatecas.png'},
  ];
  