export const cardData = [
    { title: 'Entidad num: 1', text: 'Aguscalientes', imgSrc: '/assets/icon_Aguascalientes.png',entidad:'1'},
    { title: 'Entidad num: 2', text: 'Baja California', imgSrc: '/assets/icon_Baja_california_sur.png',entidad:'2'},
    { title: 'Entidad num: 3', text: 'Baja California Sur', imgSrc: '/assets/icon_Baja_california.png',entidad:'3'},
    { title: 'Entidad num: 4', text: 'Campeche', imgSrc: '/assets/icon_Campeche.png',entidad:'4'},
    { title: 'Entidad num: 5', text: 'Coahuila', imgSrc: '/assets/icon_Coahuila.png',entidad:'5'},
    { title: 'Entidad num: 6', text: 'Colima', imgSrc: '/assets/icon_Colima.png',entidad:'6'},
    { title: 'Entidad num: 7', text: 'Chiapas', imgSrc: '/assets/icon_Chiapas.png',entidad:'7'},
    { title: 'Entidad num: 8', text: 'Chihuahua', imgSrc: '/assets/icon_Chihuahua.png',entidad:'8'},
    { title: 'Entidad num: 9', text: 'Ciudad de México', imgSrc: '/assets/icon_Ciudad_de_Mexico.png',entidad:'9'},
    { title: 'Entidad num: 10', text: 'Durango', imgSrc: '/assets/icon_Durango.png',entidad:'10'},
    { title: 'Entidad num: 11', text: 'Guanajuato', imgSrc: '/assets/icon_Guanajuato.png',entidad:'11'},
    { title: 'Entidad num: 12', text: 'Guerrero', imgSrc: '/assets/icon_Guerrero.png',entidad:'12'},
    { title: 'Entidad num: 13', text: 'Hidalgo', imgSrc: '/assets/icon_Hidalgo.png',entidad:'13'},
    { title: 'Entidad num: 14', text: 'Jalisco', imgSrc: '/assets/icon_Jalisco.png',entidad:'14'},
    { title: 'Entidad num: 15', text: 'México', imgSrc: '/assets/icon_Mexico.png',entidad:'15'},
    { title: 'Entidad num: 16', text: 'Michoacán', imgSrc: '/assets/icon_Michoacan.png',entidad:'16'},
    { title: 'Entidad num: 17', text: 'Morelos', imgSrc: '/assets/icon_Morelos.png',entidad:'17'},
    { title: 'Entidad num: 18', text: 'Nayarit', imgSrc: '/assets/icon_Nayarit.png',entidad:'18'},
    { title: 'Entidad num: 19', text: 'Nuevo León', imgSrc: '/assets/icon_Nuevo_Leon.png',entidad:'19'},
    { title: 'Entidad num: 20', text: 'Oaxaca', imgSrc: '/assets/icon_Oaxaca.png',entidad:'20'},
    { title: 'Entidad num: 21', text: 'Puebla', imgSrc: '/assets/icon_Puebla.png',entidad:'21'},
    { title: 'Entidad num: 22', text: 'Querétaro', imgSrc: '/assets/icon_Queretaro.png',entidad:'22'},
    { title: 'Entidad num: 23', text: 'Quintana Roo', imgSrc: '/assets/icon_Quintana_Roo.png',entidad:'23'},
    { title: 'Entidad num: 24', text: 'San Luis Potosí', imgSrc: '/assets/icon_San_Luis_Potosi.png',entidad:'24'},
    { title: 'Entidad num: 25', text: 'Sinaloa', imgSrc: '/assets/icon_Sinaloa.png',entidad:'25'},
    { title: 'Entidad num: 26', text: 'Sonora', imgSrc: '/assets/icon_Sonora.png',entidad:'26'},
    { title: 'Entidad num: 27', text: 'Tabasco', imgSrc: '/assets/icon_Tabasco.png',entidad:'27'},
    { title: 'Entidad num: 28', text: 'Tamaulipas', imgSrc: '/assets/icon_Tamaulipas.png',entidad:'28'},
    { title: 'Entidad num: 29', text: 'Tlaxcala', imgSrc: '/assets/icon_Tlaxcala.png',entidad:'29'},
    { title: 'Entidad num: 30', text: 'Veracruz', imgSrc: '/assets/icon_Veracruz.png',entidad:'30'},
    { title: 'Entidad num: 31', text: 'Yucatán', imgSrc: '/assets/icon_Yucatan.png',entidad:'31'},
    { title: 'Entidad num: 32', text: 'Zacatecas', imgSrc: '/assets/icon_Zacatecas.png',entidad:'32'},
  ];
  